const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const {spawn}=require('node:child_process');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const output=process.env.ARCHIVE_TEST_OUTPUT_DIR || require('node:os').tmpdir();
const server=spawn(process.env.ARCHIVE_TEST_PYTHON || 'python',[root+'/tests/browser_fixture.py'],{stdio:['ignore','ignore','pipe']});
let stderr='';server.stderr.on('data',d=>stderr+=d);
const base='http://127.0.0.1:18993';
const checks=[];let browser;
async function run(){
  for(let i=0;i<50;i++){
    try{const r=await fetch(base+'/');if(r.ok)break;}catch{}
    if(server.exitCode!==null)throw Error(stderr);
    await new Promise(r=>setTimeout(r,100));
  }
  browser=await chromium.launch({headless:true,executablePath:process.env.ARCHIVE_TEST_CHROME || (process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined)});
  const context=await browser.newContext({viewport:{width:1280,height:1000},acceptDownloads:true});
  const page=await context.newPage();
  await context.route('**/*',route => route.request().url().startsWith(base) ? route.continue() : route.abort());
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const anonymous=await browser.newContext();
  assert.equal((await anonymous.request.post(base+'/api/manage/preview',{data:{session_id:'qq:group:42'}})).status(),401);
  await anonymous.close();checks.push('unauthenticated management returns 401');
  await page.goto(base+'/?session_id=qq%3Agroup%3A42');
  await page.locator('#api-key-input').fill('synthetic-browser-only');
  await page.locator('#login-btn').click();
  await page.locator('.msg-bubble').filter({hasText:'UI message one'}).waitFor();
  const state=async()=>await (await context.request.get(base+'/api/test/state')).json();
  const initial=await state();assert.equal(initial.rows.length,3);assert.equal(initial.retention_disabled_by_default,true);
  assert.equal((await context.request.post(base+'/api/manage/preview',{data:{session_id:'qq:group:42'},headers:{Origin:'https://evil.example'}})).status(),403);
  checks.push('login works; foreign Origin denied; retention default disabled');
  await page.locator('.msg-bubble').filter({hasText:'UI message one'}).getByRole('button',{name:'管理',exact:true}).click();
  assert.equal(await page.locator('#manage-mode').inputValue(),'trash');
  assert.equal(await page.locator('#manage-confirm').isDisabled(),true);
  assert.equal(await page.locator('#manage-before').isDisabled(),true);
  await page.route('**/api/manage/preview',async route=>{await new Promise(r=>setTimeout(r,100));await route.continue();});
  await page.locator('#manage-preview').click();
  assert.equal(await page.locator('#manage-mode').isDisabled(),true);
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent.includes('本批 1 条'));
  assert.match(await page.locator('#manage-status').textContent(),/1 个共享附件/);
  await page.screenshot({path:output+'/management-browser.png',fullPage:true});
  page.once('dialog',d=>d.dismiss());
  await page.locator('#manage-confirm').click();
  assert.equal((await state()).rows.length,3);checks.push('single-message preview, shared cache, cancel causes no deletion');
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#manage-export').click();
  const download=await downloadPromise;await download.saveAs(output+'/synthetic-message-backup.json');
  const backup=JSON.parse(await fs.readFile(output+'/synthetic-message-backup.json','utf8'));
  assert.equal(backup.messages.length,1);assert.match(backup.messages[0].message,/UI message one/);
  assert.equal(backup.attachments_included,false);checks.push('JSON export saves exactly the preview batch without attachments');
  await page.waitForFunction(()=>!document.querySelector('#manage-confirm').disabled);
  let deleteRequests=0;page.on('request',r=>{if(r.url().endsWith('/api/manage/delete'))deleteRequests++;});
  page.once('dialog',d=>d.accept());
  await page.route('**/api/manage/delete',async route=>{await new Promise(r=>setTimeout(r,150));await route.continue();});
  await page.locator('#manage-confirm').click();
  await page.locator('#manage-confirm').dispatchEvent('click');
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent.includes('已移入回收站'));
  await page.waitForFunction(()=>document.querySelector('#manage-trash').textContent.includes('恢复 1 条'));
  const afterTrash=await state();assert.equal(afterTrash.rows.length,2);assert.equal(afterTrash.trash_count,1);
  assert.equal(afterTrash.cache_bytes,initial.cache_bytes);assert.equal(deleteRequests,1);
  assert.equal(await page.locator('#manage-confirm').isDisabled(),true);
  await page.locator('#manage-confirm').dispatchEvent('click');
  assert.equal(deleteRequests,1);checks.push('delete commits once, repeated click ignored, stats and shared cache preserved');
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:/恢复 1 条/}).click();
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent==='恢复成功。');
  await page.locator('.msg-bubble').filter({hasText:'UI message one'}).waitFor();
  assert.equal((await state()).rows.length,3);checks.push('restore updates message view and statistics');
  await page.locator('#manage-close').click();
  await page.locator('#manage-btn').click();
  await page.locator('#manage-preview').click();
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent.includes('本批 2 条'));
  await page.locator('#manage-before').fill('1970-01-01T00:02');
  assert.equal(await page.locator('#manage-confirm').isDisabled(),true);
  await page.locator('#manage-before').fill('');
  await page.locator('#manage-preview').click();
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent.includes('本批 2 条'));
  page.once('dialog',d=>d.dismiss());await page.locator('#manage-confirm').click();
  assert.equal((await state()).rows.length,3);checks.push('session preview, range change invalidates confirmation, cancel preserves rows');
  page.once('dialog',d=>d.accept());await page.locator('#manage-confirm').click();
  await page.getByRole('button',{name:/恢复 2 条/}).waitFor();
  assert.equal((await state()).rows.length,1);
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:/恢复 2 条/}).click();
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent==='恢复成功。');
  await page.locator('.msg-bubble').filter({hasText:'UI message one'}).waitFor();
  assert.equal((await state()).rows.length,3);
  checks.push('whole-session delete and restore preserve the other platform with the same group number');
  await page.locator('#manage-close').click();
  await page.locator('.msg-bubble').filter({hasText:'UI message one'}).getByRole('button',{name:'管理',exact:true}).click();
  await page.locator('#manage-mode').selectOption('permanent');
  await page.locator('#manage-preview').click();
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent.includes('本批 1 条'));
  let promptAnswer='wrong';const dialogs=d=>d.type()==='prompt'?d.accept(promptAnswer):d.accept();page.on('dialog',dialogs);
  await page.locator('#manage-confirm').click();
  assert.equal((await state()).rows.length,3);
  promptAnswer='永久删除';await page.locator('#manage-confirm').click();
  await page.waitForFunction(()=>document.querySelector('#manage-status').textContent.includes('已永久删除'));
  const final=await state();assert.equal(final.rows.length,2);assert.equal(final.trash_count,0);assert.equal(final.cache_bytes,initial.cache_bytes);
  assert.equal(final.stats.find(x=>x.session_id==='qq:group:42').message_count,1);
  page.removeListener('dialog',dialogs);checks.push('permanent deletion requires exact second confirmation; no trash recovery; attachments untouched');
  await page.route('**/api/dashboard?*',async route=>{await new Promise(r=>setTimeout(r,300));await route.continue();});
  await page.locator('#manage-close').click();await page.locator('#home-btn').click();
  await page.locator('#searchInput').fill('UI message');await page.locator('#searchInput').press('Enter');
  await page.waitForFunction(()=>document.querySelectorAll('.message-origin').length===2);
  await page.waitForTimeout(450);
  const origins=await page.locator('.message-origin').evaluateAll(a=>a.map(x=>({text:x.textContent,href:x.getAttribute('href')})));
  await fs.writeFile(output+'/management-browser-origins.json',JSON.stringify(origins,null,2));
  assert(origins.some(x=>x.href.includes('qq%3Agroup%3A42')));assert(origins.some(x=>x.href.includes('tg%3Agroup%3A42')));
  checks.push('home navigation and global search show distinct exact session links');
  await page.route('**/api/history?*',async route=>{
    if(new URL(route.request().url()).searchParams.get('session_id')==='qq:group:42')await new Promise(r=>setTimeout(r,300));
    await route.continue();
  });
  await page.locator('.session-item[data-session-id="qq:group:42"]').click();
  await page.locator('.session-item[data-session-id="tg:group:42"]').click();
  await page.locator('.msg-bubble').filter({hasText:'UI message other'}).waitFor();
  await page.waitForTimeout(450);
  assert.equal(await page.locator('.msg-bubble').filter({hasText:'UI message two'}).count(),0);
  assert.equal(new URL(page.url()).searchParams.get('session_id'),'tg:group:42');
  checks.push('a delayed history response cannot replace a newly selected session');
  assert.deepEqual(errors,[]);
  await fs.writeFile(output+'/management-browser-results.json',JSON.stringify({synthetic_only:true,browser:'isolated headless Chrome',checks,origins,page_errors:errors,delete_requests:deleteRequests,final_rows:final.rows.length,shared_cache_unchanged:true},null,2));
  console.log(JSON.stringify({passed:checks.length,checks},null,2));
}
run().catch(e=>{console.error(e.stack);console.error(stderr);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill('SIGTERM');});
